# Generated by Django 2.2.2 on 2019-06-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='domicio',
        ),
        migrations.AddField(
            model_name='profesor',
            name='domicilio',
            field=models.TextField(default='', help_text='Direccion de Habitacion', verbose_name='Domicilio'),
        ),
    ]
