# Generated by Django 3.0.8 on 2020-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_auto_20200802_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='rut',
            field=models.CharField(help_text='Indique su RUT', max_length=13, verbose_name='Id'),
        ),
    ]
