# Generated by Django 2.2.2 on 2019-06-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripcion del Curso', max_length=100, verbose_name='Descripcion del Curso')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionCursoProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.Profesor')),
            ],
        ),
    ]
