# Generated by Django 2.2.2 on 2019-06-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Indique su RUT', max_length=13, verbose_name='Rut')),
                ('nombres', models.CharField(help_text='Nombres y Apellidos', max_length=100, verbose_name='Nombres')),
                ('telefono', models.CharField(help_text='Numero de Telefono. ej: +56555555555', max_length=100, verbose_name='Telefono')),
                ('correo', models.EmailField(help_text='Correo Electronico', max_length=254, verbose_name='Correo Electronico')),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de Nacimiento', verbose_name='Fec. Nac.')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Masculino o Femenino', max_length=1, verbose_name='Sexo')),
                ('tipo_sangre', models.CharField(help_text='Tipo de Sangre. ej: ORH-', max_length=5, verbose_name='Tipo de Sangre')),
                ('domicio', models.TextField(help_text='Direccion de Habitacion', verbose_name='Domicio')),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
